const db = require('./db');

const seedData = async () => {
  try {
    // 1. Seed Opportunities (Hackathons, Scholarships, Jobs/Internships, Feed)
    // We want to force re-seeding if we don't see the new professional hackathons (e.g. if banner is missing)
    const hackCount = await db.Opportunity.countDocuments({ type: 'hackathon' });
    if (hackCount < 5) {
      console.log('🔄 Re-seeding database to ensure upgraded real hackathons are available...');
      if (db.dbMode === 'mongodb') {
        const mongoose = require('mongoose');
        if (mongoose.models.Opportunity) {
          await mongoose.models.Opportunity.deleteMany({});
        }
      } else {
        const fs = require('fs');
        const path = require('path');
        const filePath = path.join(__dirname, '..', 'data', 'opportunity.json');
        if (fs.existsSync(filePath)) {
          fs.writeFileSync(filePath, JSON.stringify([], null, 2));
        }
      }
    }

    const oppCount = await db.Opportunity.countDocuments();
    if (oppCount === 0) {
      console.log('🌱 Database empty. Seeding upgraded opportunities...');
      
      const opportunities = [
        {
          title: "Google Solution Challenge 2026",
          company: "Google",
          type: "hackathon",
          description: "Build a solution for one or more of the United Nations 17 Sustainable Development Goals using Google technologies.",
          eligibility: "Open to university students worldwide.",
          deadline: "2026-10-15",
          applyLink: "https://developers.google.com/community/solutions-challenge",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Google&backgroundColor=4285F4",
          tags: ["Google Cloud", "Gemini AI", "Global"],
          banner: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop",
          mode: "online",
          location: "Global / Online",
          eventDates: "Oct 20 - Nov 15, 2026",
          prizePool: "$10,000 + Google Mentorship",
          teamSize: "1-4 Members",
          regFee: "free",
          regFeeAmount: 0,
          category: "AI & Machine Learning",
          difficulty: "Intermediate",
          technologies: ["Gemini API", "Flutter", "Firebase", "GCP"],
          country: "Global",
          state: "",
          college: "",
          isFeatured: true,
          isTrending: true,
          isApproved: true,
          registrations: [],
          reviews: [
            { userId: "seeded_uid", userName: "Aarav Mehta", rating: 5, comment: "Incredible opportunity to use Google tools to solve actual human problems!", date: "2026-07-10" }
          ],
          discussions: [
            { userId: "seeded_uid", userName: "Aarav Mehta", avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Aarav", comment: "Looking for a flutter developer for our solution challenge team!", date: "2026-07-12" }
          ],
          teamFinder: [
            { id: "team1", leaderId: "seeded_uid", leaderName: "Aarav Mehta", leaderAvatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Aarav", teamName: "DevAI Innovators", description: "Building a health-tech dashboard using Gemini.", requiredSkills: ["Flutter", "Firebase"], members: ["Aarav Mehta"] }
          ]
        },
        {
          title: "Smart India Hackathon 2026",
          company: "Ministry of Education",
          type: "hackathon",
          description: "A nationwide initiative to provide students with a platform to solve some of the pressing problems we face in our daily lives.",
          eligibility: "Indian college students pursuing UG/PG/PhD.",
          deadline: "2026-08-25",
          applyLink: "https://www.sih.gov.in",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=SIH&backgroundColor=FF9933",
          tags: ["National", "Govt", "India"],
          banner: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop",
          mode: "hybrid",
          location: "Various Nodal Centers, India",
          eventDates: "Sep 15 - Sep 20, 2026",
          prizePool: "₹1,00,000 per Problem Statement",
          teamSize: "6 Members",
          regFee: "free",
          regFeeAmount: 0,
          category: "Open Innovation",
          difficulty: "Advanced",
          technologies: ["React", "Python", "Node.js", "IoT", "AI"],
          country: "India",
          state: "Delhi",
          college: "",
          isFeatured: true,
          isTrending: true,
          isApproved: true,
          registrations: [],
          reviews: [],
          discussions: [],
          teamFinder: []
        },
        {
          title: "HackHarvard 2026",
          company: "Harvard University",
          type: "hackathon",
          description: "Harvard's premier 36-hour hackathon, bringing together over 800 developers to build innovative hardware and software hacks.",
          eligibility: "Any college student aged 18+.",
          deadline: "2026-09-01",
          applyLink: "https://hackharvard.io",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Harvard&backgroundColor=A51C30",
          tags: ["Hackathon", "United States", "Networking"],
          banner: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop",
          mode: "offline",
          location: "Harvard Campus, Cambridge, MA",
          eventDates: "Oct 10 - Oct 12, 2026",
          prizePool: "$20,000",
          teamSize: "2-4 Members",
          regFee: "free",
          regFeeAmount: 0,
          category: "College Hackathons",
          difficulty: "Advanced",
          technologies: ["React", "Express", "Python", "Next.js"],
          country: "United States",
          state: "Massachusetts",
          college: "Harvard University",
          isFeatured: true,
          isTrending: false,
          isApproved: true,
          registrations: [],
          reviews: [],
          discussions: [],
          teamFinder: []
        },
        {
          title: "Devfolio Web3 Buildathon 2026",
          company: "Devfolio",
          type: "hackathon",
          description: "An intensive online buildathon for developers building next-generation blockchain and decentralized applications.",
          eligibility: "Open to all developers and blockchain enthusiasts.",
          deadline: "2026-09-15",
          applyLink: "https://devfolio.co",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Devfolio&backgroundColor=3772FF",
          tags: ["Web3", "Ethereum", "Crypto"],
          banner: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop",
          mode: "online",
          location: "Online / Global",
          eventDates: "Oct 01 - Oct 10, 2026",
          prizePool: "$25,000 in ETH",
          teamSize: "1-4 Members",
          regFee: "free",
          regFeeAmount: 0,
          category: "Blockchain",
          difficulty: "Advanced",
          technologies: ["Solidity", "Ethereum", "Rust", "Ethers.js"],
          country: "Global",
          state: "",
          college: "",
          isFeatured: true,
          isTrending: true,
          isApproved: true,
          registrations: [],
          reviews: [],
          discussions: [],
          teamFinder: []
        },
        {
          title: "HackerEarth AI Innovation Challenge",
          company: "HackerEarth",
          type: "hackathon",
          description: "Build cutting-edge artificial intelligence models and workflows to solve manufacturing efficiency bottlenecks.",
          eligibility: "Open to students and professionals.",
          deadline: "2026-08-30",
          applyLink: "https://hackerearth.com",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=HEarth&backgroundColor=323754",
          tags: ["AI", "Python", "DataScience"],
          banner: "https://images.unsplash.com/photo-1677442136019-21780efad99a?w=800&auto=format&fit=crop",
          mode: "online",
          location: "Online",
          eventDates: "Sep 10 - Sep 15, 2026",
          prizePool: "$15,000",
          teamSize: "1-3 Members",
          regFee: "free",
          regFeeAmount: 0,
          category: "AI & Machine Learning",
          difficulty: "Intermediate",
          technologies: ["Python", "TensorFlow", "Scikit-Learn", "FastAPI"],
          country: "Global",
          state: "",
          college: "",
          isFeatured: false,
          isTrending: true,
          isApproved: true,
          registrations: [],
          reviews: [],
          discussions: [],
          teamFinder: []
        },
        {
          title: "IIT Bombay Techfest Innovation Challenge",
          company: "IIT Bombay",
          type: "hackathon",
          description: "Solve mechanical, robotic, and firmware design challenges in real-time under IIT Bombay Techfest's industrial problem statement division.",
          eligibility: "Students currently enrolled in Engineering/Science streams.",
          deadline: "2026-11-10",
          applyLink: "https://techfest.org",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=IITB&backgroundColor=003366",
          tags: ["IIT", "Robotics", "Hardware"],
          banner: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop",
          mode: "offline",
          location: "IIT Bombay Campus, Powai, Mumbai",
          eventDates: "Dec 18 - Dec 20, 2026",
          prizePool: "₹5,00,000",
          teamSize: "2-4 Members",
          regFee: "free",
          regFeeAmount: 0,
          category: "Robotics",
          difficulty: "Advanced",
          technologies: ["ROS", "C++", "Arduino", "Raspberry Pi"],
          country: "India",
          state: "Maharashtra",
          college: "IIT Bombay",
          isFeatured: true,
          isTrending: false,
          isApproved: true,
          registrations: [],
          reviews: [],
          discussions: [],
          teamFinder: []
        },
        {
          title: "Microsoft Imagine Cup 2026",
          company: "Microsoft",
          type: "hackathon",
          description: "An annual global student competition that aims to give student developers the opportunity to build technology startups using Azure.",
          eligibility: "Students aged 16+ from all over the world.",
          deadline: "2026-12-01",
          applyLink: "https://imaginecup.microsoft.com",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Microsoft&backgroundColor=737373",
          tags: ["ImagineCup", "Azure", "Startup"],
          banner: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&auto=format&fit=crop",
          mode: "hybrid",
          location: "Seattle, WA / Online",
          eventDates: "Jan 15 - May 10, 2027",
          prizePool: "$100,000 + Azure Credits",
          teamSize: "1-4 Members",
          regFee: "free",
          regFeeAmount: 0,
          category: "Startup Competitions",
          difficulty: "Advanced",
          technologies: ["Azure AI", "C#", "React Native", "SQL Server"],
          country: "Global",
          state: "",
          college: "",
          isFeatured: true,
          isTrending: true,
          isApproved: true,
          registrations: [],
          reviews: [],
          discussions: [],
          teamFinder: []
        },
        {
          title: "Uber HackTag 2026",
          company: "Uber",
          type: "hackathon",
          description: "Design real-time driver allocation and routing systems on Uber's mock engineering grid. Ideal for algorithm enthusiasts.",
          eligibility: "Engineering students in pre-final and final years.",
          deadline: "2026-08-20",
          applyLink: "https://www.uber.com",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Uber&backgroundColor=000000",
          tags: ["Algorithms", "PPI", "Uber"],
          banner: "https://images.unsplash.com/photo-1549880338-65ddcdfd017b?w=800&auto=format&fit=crop",
          mode: "online",
          location: "Online / India",
          eventDates: "Sep 05 - Sep 07, 2026",
          prizePool: "₹3,00,000 + Internship PPIs",
          teamSize: "1-3 Members",
          regFee: "free",
          regFeeAmount: 0,
          category: "Coding Contests",
          difficulty: "Advanced",
          technologies: ["Java", "Go", "Python", "Data Structures"],
          country: "India",
          state: "",
          college: "",
          isFeatured: true,
          isTrending: true,
          isApproved: true,
          registrations: [],
          reviews: [],
          discussions: [],
          teamFinder: []
        },
        {
          title: "Adobe UI/UX Designathon 2026",
          company: "Adobe",
          type: "hackathon",
          description: "Design high-fidelity mockups and interaction prototypes for a future accessibility-focused student learning management system.",
          eligibility: "Open to all students interested in design.",
          deadline: "2026-09-30",
          applyLink: "https://adobe.com",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Adobe&backgroundColor=FF0000",
          tags: ["UIUX", "Design", "Figma"],
          banner: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=800&auto=format&fit=crop",
          mode: "online",
          location: "Online",
          eventDates: "Oct 15 - Oct 17, 2026",
          prizePool: "$5,000 + Creative Cloud Subscriptions",
          teamSize: "1-2 Members",
          regFee: "free",
          regFeeAmount: 0,
          category: "Design Challenges",
          difficulty: "Beginner",
          technologies: ["Figma", "Adobe XD", "UI/UX", "Illustrator"],
          country: "Global",
          state: "",
          college: "",
          isFeatured: false,
          isTrending: false,
          isApproved: true,
          registrations: [],
          reviews: [],
          discussions: [],
          teamFinder: []
        },
        {
          title: "ISRO Student Space Challenge",
          company: "ISRO",
          type: "hackathon",
          description: "Develop firmware, telemetry protocols, and payload data processing solutions for amateur satellite telemetry.",
          eligibility: "Students from ISRO-affiliated technical institutes.",
          deadline: "2026-10-30",
          applyLink: "https://www.isro.gov.in",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=ISRO&backgroundColor=0033A0",
          tags: ["SpaceTech", "ISRO", "IoT"],
          banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop",
          mode: "offline",
          location: "ISRO Satellite Integration Facility, Bangalore",
          eventDates: "Nov 25 - Nov 28, 2026",
          prizePool: "ISRO Merit Certificate & Internship Offers",
          teamSize: "3-5 Members",
          regFee: "free",
          regFeeAmount: 0,
          category: "IoT",
          difficulty: "Advanced",
          technologies: ["IoT Sensors", "MATLAB", "Python", "FPGA"],
          country: "India",
          state: "Karnataka",
          college: "",
          isFeatured: true,
          isTrending: false,
          isApproved: true,
          registrations: [],
          reviews: [],
          discussions: [],
          teamFinder: []
        },
        {
          title: "TCS CodeVita 2026",
          company: "Tata Consultancy Services",
          type: "hackathon",
          description: "The world's largest online coding contest promoting competitive coding as a sport and giving top rankers placement opportunities.",
          eligibility: "All undergraduate and postgraduate STEM students.",
          deadline: "2026-09-10",
          applyLink: "https://tcscodevita.com",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=TCS&backgroundColor=004488",
          tags: ["Coding", "Competitions", "Placement"],
          banner: "https://images.unsplash.com/photo-1605379399642-870262d3d051?w=800&auto=format&fit=crop",
          mode: "online",
          location: "Online",
          eventDates: "Sep 25 - Sep 26, 2026",
          prizePool: "$20,000 + Global Job Offers",
          teamSize: "Individual",
          regFee: "free",
          regFeeAmount: 0,
          category: "Coding Contests",
          difficulty: "Advanced",
          technologies: ["C++", "Java", "Python", "Data Structures"],
          country: "Global",
          state: "",
          college: "",
          isFeatured: false,
          isTrending: true,
          isApproved: true,
          registrations: [],
          reviews: [],
          discussions: [],
          teamFinder: []
        },
        {
          title: "Harvard Case Study Competition 2026",
          company: "Harvard Business Club",
          type: "hackathon",
          description: "Solve complex business restructuring and strategic pivot studies based on real corporate files provided by Harvard alumni.",
          eligibility: "Undergraduate business or STEM students.",
          deadline: "2026-09-20",
          applyLink: "https://harvard.edu",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=HarvardBusiness&backgroundColor=C11B17",
          tags: ["Business", "CaseStudy", "Finance"],
          banner: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop",
          mode: "hybrid",
          location: "Boston, MA / Online",
          eventDates: "Oct 05 - Oct 07, 2026",
          prizePool: "$10,000",
          teamSize: "3-4 Members",
          regFee: "free",
          regFeeAmount: 0,
          category: "Case Study Competitions",
          difficulty: "Intermediate",
          technologies: ["Finance", "Strategy", "Excel", "PowerPoint"],
          country: "United States",
          state: "Massachusetts",
          college: "Harvard University",
          isFeatured: true,
          isTrending: false,
          isApproved: true,
          registrations: [],
          reviews: [],
          discussions: [],
          teamFinder: []
        },
        {
          title: "Smart City App Challenge",
          company: "Google Developer Groups",
          type: "hackathon",
          description: "Build a native or cross-platform application to support local municipal tasks like garbage reporting and local merchant discovery.",
          eligibility: "Open to high school and college developers.",
          deadline: "2026-08-15",
          applyLink: "https://developers.google.com/community/gdg",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=GDG&backgroundColor=4285F4",
          tags: ["AppDev", "Flutter", "Firebase"],
          banner: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop",
          mode: "online",
          location: "Online",
          eventDates: "Aug 20 - Aug 25, 2026",
          prizePool: "$12,000",
          teamSize: "1-4 Members",
          regFee: "free",
          regFeeAmount: 0,
          category: "App Development",
          difficulty: "Beginner",
          technologies: ["Flutter", "Kotlin", "Swift", "Firebase"],
          country: "Global",
          state: "",
          college: "",
          isFeatured: false,
          isTrending: true,
          isApproved: true,
          registrations: [],
          reviews: [],
          discussions: [],
          teamFinder: []
        },
        {
          title: "Google Generation Scholarship (APAC)",
          company: "Google",
          provider: "Google APAC",
          type: "scholarship",
          description: "Established to help aspiring computer scientists excel in technology and become leaders in the field. Selected students receive $2,500 USD.",
          eligibility: "Female students currently enrolled as full-time undergraduates in a university for Computer Science or related STEM fields.",
          deadline: "2026-09-15",
          applyLink: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=GoogleGen&backgroundColor=34A853",
          tags: ["WomenInTech", "STEM", "Google"],
          banner: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&auto=format&fit=crop",
          mode: "online",
          amount: "$2,500 USD",
          educationLevel: "Undergraduate",
          scholarshipType: "Merit-based",
          isGovernment: false,
          state: "All India",
          category: "General",
          documents: ["Resume", "Academic Transcripts", "Essay Submissions"]
        },
        {
          title: "Reliance Foundation Postgraduate Scholarship",
          company: "Reliance Foundation",
          provider: "Reliance Foundation",
          type: "scholarship",
          description: "Supporting India's brightest minds in AI, Computer Science, Mathematics, and renewable energy with up to INR 6 Lakhs over the course of the degree.",
          eligibility: "First-year postgraduate students in India pursuing designated STEM courses with minimum 7.5 CGPA in graduation.",
          deadline: "2026-10-31",
          applyLink: "https://www.reliancefoundation.org",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Reliance&backgroundColor=003366",
          tags: ["Postgrad", "STEM", "RenewableEnergy"],
          banner: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&auto=format&fit=crop",
          mode: "online",
          amount: "₹6,00,000",
          educationLevel: "Postgraduate / PhD",
          scholarshipType: "Merit-based",
          isGovernment: false,
          state: "All India",
          category: "General",
          documents: ["Graduation Marksheet", "Income Certificate", "Passport Photo"]
        },
        {
          title: "NSP Central Sector Scheme of Scholarship",
          company: "Ministry of Education",
          provider: "Department of Higher Education (Govt of India)",
          type: "scholarship",
          description: "Assisting meritorious students from financially weaker families to meet a part of their day-to-day expenses while pursuing higher studies.",
          eligibility: "Students above 80th percentile in class 12 board exams, enrolled in regular courses and family income < ₹4.5L per annum.",
          deadline: "2026-12-15",
          applyLink: "https://scholarships.gov.in",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=NSP&backgroundColor=FF9933",
          tags: ["Government", "Merit-cum-Means", "HigherStudies"],
          banner: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop",
          mode: "online",
          amount: "₹20,000 per year",
          educationLevel: "Undergraduate",
          scholarshipType: "Merit-cum-Means",
          isGovernment: true,
          state: "All India",
          category: "General",
          documents: ["Class 12 Marksheet", "Income Certificate", "Caste Certificate (if applicable)", "Bank Passbook"]
        },
        {
          title: "AICTE Pragati Scholarship for Girl Students",
          company: "AICTE",
          provider: "All India Council for Technical Education (Govt of India)",
          type: "scholarship",
          description: "An initiative by the Government of India to support girls pursuing technical education (degree or diploma) at AICTE-approved institutions.",
          eligibility: "Maximum two girls per family with family income < ₹8L per annum, enrolled in 1st year of Degree/Diploma course.",
          deadline: "2026-11-30",
          applyLink: "https://www.aicte-india.org/schemes/students-development-schemes/pragati-scholarship-scheme",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=AICTE&backgroundColor=0033A0",
          tags: ["Government", "WomenInTech", "TechnicalEducation"],
          banner: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&auto=format&fit=crop",
          mode: "online",
          amount: "₹50,000 per year",
          educationLevel: "Undergraduate",
          scholarshipType: "Need-based",
          isGovernment: true,
          state: "All India",
          category: "General",
          documents: ["Admission Letter", "Tuition Fee Receipt", "Income Certificate", "Aadhaar Card"]
        },
        {
          title: "HDFC Bank Parivartan ECSS Scholarship",
          company: "HDFC Bank",
          provider: "HDFC Bank",
          type: "scholarship",
          description: "Assisting students from underprivileged families in pursuing higher education. Covers school, diploma, UG, and PG programs.",
          eligibility: "Indian students enrolled in PG, UG, or Diploma courses with minimum 55% marks in previous class and family income < ₹2.5L.",
          deadline: "2026-09-30",
          applyLink: "https://www.buddy4study.com/page/hdfc-bank-parivartan-ecss-scholarship",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=HDFC&backgroundColor=1A365D",
          tags: ["Private", "Underprivileged", "FinancialAid"],
          banner: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&auto=format&fit=crop",
          mode: "online",
          amount: "₹75,000",
          educationLevel: "Undergraduate / MBA",
          scholarshipType: "Need-based",
          isGovernment: false,
          state: "All India",
          category: "General",
          documents: ["Previous Class Marksheet", "Income Proof", "Current Admission Proof", "Student Bank Account Details"]
        },
        {
          title: "Tata Trusts Scholarship for UG and PG",
          company: "Tata Trusts",
          provider: "Tata Trusts",
          type: "scholarship",
          description: "Providing financial assistance to meritorious students wishing to pursue higher studies in Medical Sciences, Healthcare, and Engineering streams.",
          eligibility: "Indian students enrolled in medical or engineering courses at recognized Indian universities.",
          deadline: "2026-10-15",
          applyLink: "https://www.tatatrusts.org/our-areas-of-work/education/scholarships",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Tata&backgroundColor=003366",
          tags: ["Private", "Engineering", "Medical"],
          banner: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop",
          mode: "online",
          amount: "₹50,000",
          educationLevel: "Undergraduate",
          scholarshipType: "Merit-based",
          isGovernment: false,
          state: "All India",
          category: "General",
          documents: ["Marksheet of Qualifying Exam", "Fee Receipt", "Cancelled Cheque", "Salary Slip of Parents"]
        },
        {
          title: "LIC Golden Jubilee Scholarship Scheme",
          company: "LIC",
          provider: "Life Insurance Corporation of India",
          type: "scholarship",
          description: "Awarded to meritorious students from economically weaker families to provide them better opportunities for higher education in medicine, engineering, etc.",
          eligibility: "Students who have passed Class 12 (or equivalent) with minimum 60% marks and family income < ₹2.5L.",
          deadline: "2026-12-31",
          applyLink: "https://licindia.in/golden-jubilee-foundation-scholarship-scheme",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=LIC&backgroundColor=E0A900",
          tags: ["Government-Backed", "LIC", "EconomicWeak"],
          banner: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&auto=format&fit=crop",
          mode: "online",
          amount: "₹20,000 per year",
          educationLevel: "Undergraduate",
          scholarshipType: "Need-based",
          isGovernment: true,
          state: "All India",
          category: "General",
          documents: ["Birth Certificate", "Income Certificate", "Class 12 Marksheet", "Declaration from Parents"]
        },
        {
          title: "ONGC Scholarship for Merit Students",
          company: "ONGC",
          provider: "ONGC Foundation",
          type: "scholarship",
          description: "Providing financial aid to meritorious students belonging to SC/ST/OBC and General categories pursuing professional courses.",
          eligibility: "First-year UG Engineering/MBBS or PG MBA/Geology students with 60%+ marks and family income < ₹4.5L.",
          deadline: "2026-10-30",
          applyLink: "https://www.ongcscholar.org",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=ONGC&backgroundColor=E30A17",
          tags: ["ReservedCategory", "ONGC", "ProfessionalCourses"],
          banner: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop",
          mode: "online",
          amount: "₹48,00,000 per year",
          educationLevel: "Undergraduate / MBA",
          scholarshipType: "Merit-cum-Means",
          isGovernment: true,
          state: "All India",
          category: "SC/ST/OBC",
          documents: ["Income Certificate", "Caste Certificate", "Aadhaar Card", "Class 12/Graduation Marksheet"]
        },
        {
          title: "Aditya Birla Group Scholarship Scheme",
          company: "Aditya Birla Group",
          provider: "Aditya Birla Group",
          type: "scholarship",
          description: "An annual scholarship awarded to top students from select institutions like IITs, IIMs, BITS, and Law Colleges to nurture future leaders.",
          eligibility: "Top students selected through campus nomination at partner elite institutes (IITs, IIMs, BITS Pilani).",
          deadline: "2026-09-10",
          applyLink: "http://www.adityabirlascholars.net",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Birla&backgroundColor=8A1538",
          tags: ["Elite", "Leadership", "Premium"],
          banner: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&auto=format&fit=crop",
          mode: "online",
          amount: "₹1,75,000 per year",
          educationLevel: "Undergraduate / MBA",
          scholarshipType: "Merit-based",
          isGovernment: false,
          state: "All India",
          category: "General",
          documents: ["Birla Scholarship Application Form", "Academic Record", "Essays", "Letters of Recommendation"]
        },
        {
          title: "UGC Post-Graduate Indira Gandhi Scholarship",
          company: "UGC",
          provider: "University Grants Commission (Govt of India)",
          type: "scholarship",
          description: "Established to support female students who are the single girl child of their family in pursuing postgraduate education.",
          eligibility: "Female students up to 30 years of age who are the single girl child of their family, enrolled in a regular PG course.",
          deadline: "2026-11-15",
          applyLink: "https://scholarships.gov.in",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=UGC&backgroundColor=006699",
          tags: ["Government", "SingleGirlChild", "Postgrad"],
          banner: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop",
          mode: "online",
          amount: "₹36,200 per year",
          educationLevel: "Postgraduate / PhD",
          scholarshipType: "Merit-based",
          isGovernment: true,
          state: "All India",
          category: "General",
          documents: ["Single Girl Child Affidavit", "Admission Proof", "Marksheet of Graduation", "Aadhaar Card"]
        },
        {
          title: "Software Engineering Internship (Summer 2027)",
          company: "Google",
          type: "internship",
          provider: "Google Careers",
          description: "Join Google's engineering team to build scalable services, platforms, and products. Work with Google Cloud, Search, or Android teams.",
          eligibility: "Currently pursuing a Bachelor’s, Master’s or PhD degree in Computer Science or related technical field.",
          deadline: "2026-09-30",
          applyLink: "https://careers.google.com",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Google&backgroundColor=4285F4",
          tags: ["Software Engineering", "Python", "Google", "Remote"],
          banner: "https://images.unsplash.com/photo-1542744094-3a31f103e35f?w=800&auto=format&fit=crop",
          mode: "online",
          stipend: "₹1,00,000 / month",
          duration: "3 Months",
          skills: ["Python", "Java", "C++", "DSA"],
          openings: 15,
          website: "https://google.com"
        },
        {
          title: "Software Engineering Intern",
          company: "Microsoft",
          type: "internship",
          provider: "Microsoft Careers",
          description: "Apply your computer science skills to build tools, platforms, and apps at Microsoft. Work on Azure Cloud platforms or Windows core codebase.",
          eligibility: "Pre-final year B.Tech/M.Tech/MCA students graduating in 2028.",
          deadline: "2026-10-15",
          applyLink: "https://careers.microsoft.com",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Microsoft&backgroundColor=0078D4",
          tags: ["Azure", "Cloud", "C#", "Hybrid"],
          banner: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop",
          mode: "hybrid",
          stipend: "₹1,25,000 / month",
          duration: "2 Months",
          skills: ["C#", "C++", "Azure", "SQL"],
          openings: 20,
          website: "https://microsoft.com"
        },
        {
          title: "Software Development Engineer (SDE) Intern",
          company: "Amazon",
          type: "internship",
          provider: "Amazon Jobs",
          description: "Work on Amazon's consumer website, AWS cloud offerings, or logistics routing engines. Solve real-world scale and optimization problems.",
          eligibility: "Students pursuing Computer Science/IT/ECE engineering with solid analytical skills.",
          deadline: "2026-11-20",
          applyLink: "https://amazon.jobs",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Amazon&backgroundColor=FF9900",
          tags: ["Amazon", "AWS", "Backend", "Onsite"],
          banner: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop",
          mode: "offline",
          stipend: "₹80,000 / month",
          duration: "6 Months",
          skills: ["Java", "Spring Boot", "AWS", "DSA"],
          openings: 10,
          website: "https://amazon.com"
        },
        {
          title: "Associate Software Engineer Intern",
          company: "Zoho",
          type: "internship",
          provider: "Zoho Careers",
          description: "Work closely with our product builders to build robust SaaS applications. Gain experience in Zoho Creator, JavaScript components, and databases.",
          eligibility: "Open to B.E, B.Tech, MCA, M.Sc graduates or final-year students.",
          deadline: "2026-08-30",
          applyLink: "https://www.zoho.com/careers/",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Zoho&backgroundColor=E21A22",
          tags: ["SaaS", "JavaScript", "Database", "Onsite"],
          banner: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop",
          mode: "offline",
          stipend: "₹35,000 / month",
          duration: "6 Months",
          skills: ["JavaScript", "HTML", "CSS", "SQL"],
          openings: 30,
          website: "https://zoho.com"
        },
        {
          title: "Deep Learning & AI Research Intern",
          company: "NVIDIA",
          type: "internship",
          provider: "NVIDIA Careers",
          description: "Push the boundaries of modern AI computing. Work on CUDA profiling, PyTorch acceleration pipelines, or vision models.",
          eligibility: "M.Tech/PhD candidates specializing in AI, Machine Learning, or GPU programming.",
          deadline: "2026-12-10",
          applyLink: "https://nvidia.com/careers",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=NVIDIA&backgroundColor=76B900",
          tags: ["AI", "Deep Learning", "PyTorch", "Hybrid"],
          banner: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop",
          mode: "hybrid",
          stipend: "₹1,50,000 / month",
          duration: "6 Months",
          skills: ["Python", "PyTorch", "C++", "CUDA"],
          openings: 5,
          website: "https://nvidia.com"
        },
        {
          title: "Cybersecurity Consulting Intern",
          company: "Deloitte",
          type: "internship",
          provider: "Deloitte Careers",
          description: "Assist client organizations in identifying and mitigating security risks. Perform vulnerability assessments and pen testing.",
          eligibility: "Students pursuing engineering or computer applications with a focus on Information Security.",
          deadline: "2026-09-15",
          applyLink: "https://jobsindia.deloitte.com",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Deloitte&backgroundColor=86BC25",
          tags: ["Cybersecurity", "Risk Advisory", "Consulting", "Onsite"],
          banner: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop",
          mode: "offline",
          stipend: "₹30,000 / month",
          duration: "3 Months",
          skills: ["Linux", "Pen Testing", "Wireshark", "SQL"],
          openings: 12,
          website: "https://deloitte.com"
        },
        {
          title: "Network Engineer Intern",
          company: "Cisco",
          type: "internship",
          provider: "Cisco Careers",
          description: "Gain hands-on experience with routing protocols, firewall rules, and virtual networks using Cisco hardware and packet tracer.",
          eligibility: "B.Tech/BE in Electronics, Telecommunication, or Computer Science.",
          deadline: "2026-10-30",
          applyLink: "https://careers.cisco.com",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Cisco&backgroundColor=00b4d8",
          tags: ["Networks", "Routing", "Cisco", "Remote"],
          banner: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop",
          mode: "online",
          stipend: "₹50,000 / month",
          duration: "6 Months",
          skills: ["CCNA", "Linux", "Networking", "Python"],
          openings: 15,
          website: "https://cisco.com"
        },
        {
          title: "Tata Research Development Intern",
          company: "TCS",
          type: "internship",
          provider: "TCS Careers",
          description: "Work on cutting-edge research in software architecture, physical sciences, or human-computer interaction in TCS Research labs.",
          eligibility: "Final year B.Tech/M.Tech/PhD students in computer science/IT or allied fields.",
          deadline: "2026-11-15",
          applyLink: "https://www.tcs.com/careers",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=TCS&backgroundColor=E91C24",
          tags: ["Research", "Algorithms", "Tata", "Hybrid"],
          banner: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&auto=format&fit=crop",
          mode: "hybrid",
          stipend: "₹25,000 / month",
          duration: "3 Months",
          skills: ["Python", "Algorithms", "Data Science", "Research"],
          openings: 25,
          website: "https://tcs.com"
        },
        {
          title: "Frontend Engineering Intern (React)",
          company: "Wellfound Startups",
          type: "internship",
          provider: "Wellfound (AngelList)",
          description: "Join a fast-growing early stage Web3 startup. Design and implement sleek frontend components using Tailwind CSS and React hooks.",
          eligibility: "Students or self-taught developers with a strong frontend portfolio in React.",
          deadline: "2026-08-20",
          applyLink: "https://wellfound.com",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Wellfound&backgroundColor=000000",
          tags: ["React", "Frontend", "Tailwind", "Remote"],
          banner: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop",
          mode: "online",
          stipend: "₹40,000 / month",
          duration: "3 Months",
          skills: ["React", "HTML", "CSS", "Tailwind CSS", "JavaScript"],
          openings: 4,
          website: "https://wellfound.com"
        },
        {
          title: "Web Development Intern (Unpaid / Experience)",
          company: "Internshala",
          type: "internship",
          provider: "Internshala Portal",
          description: "Gain hands-on work experience by helping build non-profit community services. Mentorship from senior software engineers.",
          eligibility: "Students seeking academic credit or hands-on practice in HTML/CSS/JS.",
          deadline: "2026-08-10",
          applyLink: "https://internshala.com",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=Internshala&backgroundColor=1295D8",
          tags: ["HTML", "CSS", "JS", "Remote", "Unpaid"],
          banner: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop",
          mode: "online",
          stipend: "Unpaid (Certificate + LOR)",
          duration: "1 Month",
          skills: ["HTML", "CSS", "JavaScript"],
          openings: 50,
          website: "https://internshala.com"
        },
        {
          title: "AI/ML Engineer Associate",
          company: "OpenAI",
          type: "job",
          description: "Design and implement systems that evaluate and align next-generation frontier models. Build scalable tooling and data analysis pipelines.",
          eligibility: "New graduates or final-year university students with strong Python and ML foundations.",
          deadline: "2026-08-15",
          applyLink: "https://openai.com/careers",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=OpenAI&backgroundColor=10a37f",
          tags: ["San Francisco", "AI", "Machine Learning"],
          banner: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=800&auto=format&fit=crop",
          mode: "offline"
        },
        {
          title: "Free AWS Cloud Practitioner Certification",
          company: "Amazon Web Services",
          type: "course",
          description: "Full AWS Cloud Practitioner training course, including virtual labs, practice questions, and a 50% discount voucher for the certification exam.",
          eligibility: "Open to all students with an institutional email (.edu).",
          deadline: "2026-12-31",
          applyLink: "https://aws.amazon.com/education/aws-educate/",
          logo: "https://api.dicebear.com/7.x/initials/svg?seed=AWS&backgroundColor=FF9900",
          tags: ["AWS", "Cloud", "Certification"],
          banner: "https://images.unsplash.com/photo-1484417894907-623942c8ea29?w=800&auto=format&fit=crop",
          mode: "online"
        }
      ];

      for (const opp of opportunities) {
        if (!opp.platform && opp.type === 'hackathon') {
          const comp = (opp.company || '').toLowerCase();
          if (comp.includes('google')) opp.platform = 'Devpost';
          else if (comp.includes('harvard')) opp.platform = 'Devpost';
          else if (comp.includes('microsoft')) opp.platform = 'Devpost';
          else if (comp.includes('adobe')) opp.platform = 'Devpost';
          else if (comp.includes('devfolio')) opp.platform = 'Devfolio';
          else if (comp.includes('hackerearth')) opp.platform = 'HackerEarth';
          else opp.platform = 'Unstop';
        }
        await db.Opportunity.create(opp);
      }
      console.log('✅ Seeded opportunities.');

      // Dynamically sync Hack Club and Devpost RSS live events
      try {
        console.log('🔄 Syncing live events from Hack Club and Devpost RSS...');
        const { syncOpportunities } = require('../utils/apiSync');
        await syncOpportunities();
        console.log('✅ Successfully completed initial live sync.');
      } catch (syncErr) {
        console.error('⚠️ Initial live sync failed during seeding:', syncErr.message);
      }
    }

    // 2. Seed Events (Calendar workshops)
    const eventCount = await db.Event.countDocuments();
    if (eventCount === 0) {
      const events = [
        {
          title: "Generative AI Hackathon Prep Masterclass",
          description: "Learn how to build and deploy GenAI applications using Gemini APIs. We will cover prompt engineering, function calling, and vector search.",
          date: "2026-07-25",
          time: "18:00 - 19:30 IST",
          venue: "Google Meet / YouTube Live",
          speaker: "Amit Kumar (GDE in Cloud & AI)",
          registrationLink: "https://studora.io/workshops/genai-prep",
          tags: ["AI", "Gemini API", "Hackathon"],
          rsvps: []
        },
        {
          title: "Web Development Trends: React 19 & Next.js 15",
          description: "Explore the new features of React 19 including server actions, useActionState, asset loading, and compiler optimizations.",
          date: "2026-07-28",
          time: "15:00 - 16:30 IST",
          venue: "Seminar Hall A / Virtual Zoom",
          speaker: "Sarah Jenkins (Senior Frontend Architect)",
          registrationLink: "https://studora.io/workshops/react19",
          tags: ["React", "Frontend", "Javascript"],
          rsvps: []
        },
        {
          title: "Cracking FAANG Interviews: DSA & System Design",
          description: "A step-by-step roadmap to building your DSA skills, optimizing LeetCode patterns, and navigating complex system architecture interviews.",
          date: "2026-08-05",
          time: "10:00 - 12:00 IST",
          venue: "Main Auditorium",
          speaker: "Ex-Google Staff Engineer",
          registrationLink: "https://studora.io/workshops/faang-prep",
          tags: ["Placement", "DSA", "Interviews"],
          rsvps: []
        }
      ];

      for (const ev of events) {
        await db.Event.create(ev);
      }
      console.log('✅ Seeded events/workshops.');
    }

    // 3. Seed Study Resources
    const resCount = await db.Resource.countDocuments();
    if (resCount === 0) {
      const resources = [
        {
          title: "Computer Networks & TCP/IP Reference Notes",
          subject: "Computer Networks",
          type: "note",
          link: "https://www.w3.org/People/Frystyk/book/HTTP.html",
          uploaderName: "Dr. Ramesh Prasad",
          uploaderId: "admin_seed_id"
        },
        {
          title: "Database Management Systems (DBMS) PYQ Solved PDF (2020-2025)",
          subject: "DBMS",
          type: "pyq",
          link: "https://web.stanford.edu/class/cs145/",
          uploaderName: "Kunal Verma (CS President)",
          uploaderId: "admin_seed_id"
        },
        {
          title: "Operating Systems (OS) Lecture Slides & Syllabus",
          subject: "Operating Systems",
          type: "syllabus",
          link: "https://pages.cs.wisc.edu/~remzi/OSTEP/",
          uploaderName: "Prof. Clara Oswald",
          uploaderId: "admin_seed_id"
        },
        {
          title: "MERN Stack Full-Course Playlist (60 Videos)",
          subject: "Web Development",
          type: "playlist",
          link: "https://youtube.com/playlist?list=PL4cUxeGkcC9gcy9l8-QDGIqi5ZgFTg3yY",
          uploaderName: "WebDev Community",
          uploaderId: "admin_seed_id"
        }
      ];

      for (const res of resources) {
        await db.Resource.create(res);
      }
      console.log('✅ Seeded study resources.');
    }

    // 4. Seed Community discussions
    const disCount = await db.Discussion.countDocuments();
    if (disCount === 0) {
      const discussions = [
        {
          title: "Looking for 2 Frontend Developers (React) for Google Solution Challenge!",
          content: "Hey folks! We have an idea around educational accessibility (UN Goal 4) utilizing LLMs. We have a Python Flask backend ready and need 2 React/Tailwind developers to build the web UI. Ping me or drop a comment if interested!",
          authorName: "Ananya Iyer",
          authorId: "seed_ananya_id",
          type: "teammate_search",
          tags: ["Hackathon", "React", "Gemini"],
          comments: [
            {
              authorName: "Rohit Sharma",
              content: "Hey Ananya! I am a React dev with experience in Framer Motion. I'd love to join! Let's connect on Discord.",
              createdAt: new Date().toISOString()
            }
          ]
        },
        {
          title: "How to prepare for LeetCode Medium/Hard patterns?",
          content: "I've solved around 150 LeetCode Easy questions, but I get stuck when starting Mediums, especially Dynamic Programming and Graphs. Any advice on how to structure my practice?",
          authorName: "Vikram Malhotra",
          authorId: "seed_vikram_id",
          type: "discussion",
          tags: ["DSA", "LeetCode", "Placement"],
          comments: [
            {
              authorName: "Aishwarya R.",
              content: "Try sorting by pattern (e.g. Sliding Window, Two Pointers). For Dynamic Programming, start with 1D DP (Fibonacci, Climbing Stairs) before jumping to 2D DP. Don't spend more than 45 mins on a problem; read the editorial afterwards!",
              createdAt: new Date().toISOString()
            }
          ]
        }
      ];

      for (const dis of discussions) {
        await db.Discussion.create(dis);
      }
      console.log('✅ Seeded community discussions.');
    }

    // 5. Seed Certifications / Free Courses
    const certCount = await db.Certification.countDocuments();
    if (certCount === 0) {
      console.log('🌱 Seeding certifications...');
      const certifications = [
        {
          title: "Data Analytics Virtual Experience",
          companyName: "Tata Group",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=Tata&backgroundColor=003366",
          category: "Data Analytics",
          description: "Analyze real-world business scenarios, prepare interactive dashboards using Tableau/Power BI, and provide strategic recommendations for Tata Group leadership.",
          skills: ["Data Visualization", "Tableau", "Power BI", "Data Interpretation", "Strategic Thinking"],
          duration: "3-4 hours",
          difficulty: "Beginner",
          isFreeCertificate: true,
          isVirtualExperience: true,
          provider: "The Forage",
          courseLink: "https://www.theforage.com/simulations/tata-group/data-visualisation-empowering-business-with-effective-insights-z5hw",
          isFeatured: true,
          views: 120,
          completions: 34
        },
        {
          title: "Technology Consulting Virtual Experience",
          companyName: "Deloitte",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=Deloitte&backgroundColor=86BC25",
          category: "Consulting",
          description: "Step into the shoes of a Deloitte technology consultant. Solve issues related to cloud infrastructure selection, API development, and data security strategy.",
          skills: ["Cloud Migration", "API Design", "Cybersecurity", "Client Presentation", "Technology Strategy"],
          duration: "5-6 hours",
          difficulty: "Intermediate",
          isFreeCertificate: true,
          isVirtualExperience: true,
          provider: "The Forage",
          courseLink: "https://www.theforage.com/simulations/deloitte-uk/technology-consulting-virtual-experience-program",
          isFeatured: true,
          views: 198,
          completions: 56
        },
        {
          title: "Software Engineering Virtual Experience",
          companyName: "JPMorgan Chase & Co.",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=JPM&backgroundColor=1D2F54",
          category: "Software Engineering",
          description: "Build financial visualization dashboards, fix existing repo bugs, work with JPMorgan's open-source library perspective, and utilize Git for collaborative development.",
          skills: ["React", "Python", "TypeScript", "Perspective", "Git & GitHub"],
          duration: "4-5 hours",
          difficulty: "Beginner",
          isFreeCertificate: true,
          isVirtualExperience: true,
          provider: "The Forage",
          courseLink: "https://www.theforage.com/simulations/jpmorgan-chase/software-engineering-lite-jpmc",
          isFeatured: true,
          views: 310,
          completions: 92
        },
        {
          title: "Developer Program Virtual Experience",
          companyName: "Accenture",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=Accenture&backgroundColor=A12BFF",
          category: "Software Engineering",
          description: "Work on system design architecture, code reviews, debugging software interfaces, and deploying containerized applications for Accenture's tech clients.",
          skills: ["System Design", "Code Review", "Docker", "Debugging", "Agile Methodology"],
          duration: "5-6 hours",
          difficulty: "Intermediate",
          isFreeCertificate: true,
          isVirtualExperience: true,
          provider: "The Forage",
          courseLink: "https://www.theforage.com/simulations/accenture-nordics/developer-program",
          isFeatured: false,
          views: 95,
          completions: 21
        },
        {
          title: "Digital Assurance Virtual Experience",
          companyName: "PwC",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=PwC&backgroundColor=DC143C",
          category: "Consulting",
          description: "Help clients navigate digital transformations, evaluate cybersecurity threats, and analyze governance models to ensure risk-free operations.",
          skills: ["Risk Assessment", "Digital Auditing", "Cybersecurity Strategy", "IT Governance"],
          duration: "4-5 hours",
          difficulty: "Intermediate",
          isFreeCertificate: true,
          isVirtualExperience: true,
          provider: "PwC",
          courseLink: "https://www.theforage.com/simulations/pwc-australia/digital-assurance-program-vmph",
          isFeatured: false,
          views: 84,
          completions: 18
        },
        {
          title: "Strategy Consulting Virtual Experience",
          companyName: "BCG",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=BCG&backgroundColor=008A4B",
          category: "Consulting",
          description: "Work on strategic market research, profitability analysis, and competitive landscape mapping for BCG's top-tier international corporate clients.",
          skills: ["Market Entry Strategy", "Financial Modeling", "Strategic Thinking", "Sizing Market"],
          duration: "6-8 hours",
          difficulty: "Advanced",
          isFreeCertificate: true,
          isVirtualExperience: true,
          provider: "The Forage",
          courseLink: "https://www.theforage.com/simulations/bcg/strategy-consulting-virtual-experience-program",
          isFeatured: true,
          views: 145,
          completions: 40
        },
        {
          title: "Career Accelerator Virtual Experience",
          companyName: "KPMG",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=KPMG&backgroundColor=00338D",
          category: "Data Analytics",
          description: "Perform data quality audits, identify customer behavior trends, and compile interactive executive briefings for corporate strategy development.",
          skills: ["Data Auditing", "Data Cleaning", "Data Analytics", "Client Presentation"],
          duration: "3-4 hours",
          difficulty: "Beginner",
          isFreeCertificate: true,
          isVirtualExperience: true,
          provider: "The Forage",
          courseLink: "https://www.theforage.com/simulations/kpmg-us/career-accelerator-data-analytics",
          isFeatured: false,
          views: 73,
          completions: 15
        },
        {
          title: "Software Engineering Simulation",
          companyName: "Electronic Arts (EA)",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=EA&backgroundColor=FF0000",
          category: "Software Engineering",
          description: "Simulate game development loops, resolve runtime optimization bugs, and write clean C++ scripts to control game engine UI rendering states.",
          skills: ["C++", "Game Optimization", "Algorithm Design", "Memory Management"],
          duration: "4-5 hours",
          difficulty: "Advanced",
          isFreeCertificate: true,
          isVirtualExperience: true,
          provider: "The Forage",
          courseLink: "https://www.theforage.com/simulations/electronic-arts/software-engineering-ea",
          isFeatured: true,
          views: 220,
          completions: 49
        },
        {
          title: "Cybersecurity Virtual Experience",
          companyName: "Mastercard",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=Mastercard&backgroundColor=FF5F00",
          category: "Cybersecurity",
          description: "Identify phishing domains, perform network penetration analysis, and establish enterprise cybersecurity defense roadmaps for Mastercard partners.",
          skills: ["Threat Intelligence", "Phishing Analysis", "Firewall Configuration", "Risk Mitigation"],
          duration: "5-6 hours",
          difficulty: "Intermediate",
          isFreeCertificate: true,
          isVirtualExperience: true,
          provider: "The Forage",
          courseLink: "https://www.theforage.com/simulations/mastercard/cybersecurity-mastercard",
          isFeatured: false,
          views: 110,
          completions: 27
        },
        {
          title: "Google Cloud Fundamentals: Core Infrastructure",
          companyName: "Google",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=Google&backgroundColor=4285F4",
          category: "Cloud Computing",
          description: "Learn about the critical computing and storage services available in Google Cloud Platform (GCP), including Compute Engine and Google Kubernetes Engine.",
          skills: ["Google Cloud Platform", "Cloud Infrastructure", "Kubernetes", "IAM Rules"],
          duration: "8-10 hours",
          difficulty: "Beginner",
          isFreeCertificate: true,
          isVirtualExperience: false,
          provider: "Google",
          courseLink: "https://www.cloudskillsboost.google/course_templates/2",
          isFeatured: true,
          views: 450,
          completions: 180
        },
        {
          title: "Microsoft Azure AI Fundamentals",
          companyName: "Microsoft",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=Microsoft&backgroundColor=00A4EF",
          category: "Artificial Intelligence",
          description: "Demonstrate knowledge of common ML and AI workloads and how to implement them on Microsoft Azure. Prepares you for the AI-900 exam.",
          skills: ["Azure Cloud", "Machine Learning", "Cognitive Services", "Computer Vision"],
          duration: "12-15 hours",
          difficulty: "Beginner",
          isFreeCertificate: true,
          isVirtualExperience: false,
          provider: "Microsoft",
          courseLink: "https://learn.microsoft.com/en-us/training/paths/azure-ai-fundamentals/",
          isFeatured: true,
          views: 389,
          completions: 145
        },
        {
          title: "AWS Cloud Practitioner Essentials",
          companyName: "AWS",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=AWS&backgroundColor=FF9900",
          category: "Cloud Computing",
          description: "Get a detailed overview of cloud concepts, AWS services, security, architecture, pricing, and support to build AWS cloud competence.",
          skills: ["AWS Services", "Cloud Architecture", "Billing & Pricing", "IAM Security"],
          duration: "6 hours",
          difficulty: "Beginner",
          isFreeCertificate: true,
          isVirtualExperience: false,
          provider: "AWS",
          courseLink: "https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/",
          isFeatured: false,
          views: 290,
          completions: 98
        },
        {
          title: "Scientific Computing with Python",
          companyName: "freeCodeCamp",
          companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=FCC&backgroundColor=0A0A23",
          category: "Software Engineering",
          description: "Learn Python fundamentals, data structures, algorithms, and build several scientific computing calculators to earn a verified developer certificate.",
          skills: ["Python", "Algorithms", "Data Structures", "Scientific Calculations"],
          duration: "300 hours",
          difficulty: "Intermediate",
          isFreeCertificate: true,
          isVirtualExperience: false,
          provider: "freeCodeCamp",
          courseLink: "https://www.freecodecamp.org/learn/scientific-computing-with-python/",
          isFeatured: false,
          views: 520,
          completions: 110
        }
      ];

      for (const cert of certifications) {
        await db.Certification.create(cert);
      }
      console.log('✅ Seeded certifications.');
    }
  } catch (err) {
    console.error('Error seeding database:', err);
  }
};

module.exports = seedData;
